list = [1, 2, 4 ,5 ,6]
print(list)
list.append(9)
print('.append is used to add item in the list')
print(list)
list.insert(0,22)
print('''.insert is used to add item at specific location in your list by telling the index, value''')
print(list)
print(".remove will remove the specific value in the list")
list.remove(5)
print(list)
print(".pop remove last item from the list")
list.pop()
print(list)
print(".index show the index of specific value")
print(list.index(4))
print("'in' is used to check specific number is there or not ")
print(50 in list)
list.append(4)
print(".count tell the number of count of value in that list")
print(list.count(4))
list1= list.copy()
print(".copy is used to copy the list")
print(list1)
print(".sort is used to sort in ascending order")
list.sort()
print(list)
print(".reverse is used to sort in descending order")
list.reverse()
print(list)
print(".clear is used to clear the list")
list.clear()
print(list)
